import { ISortOption } from "../types";

export const sortOptions: ISortOption[] = [
  {
    value: "default",
    label: "Without sorting",
  },
  {
    value: "ascCost",
    label: "Asc Cost",
  },
  {
    value: "descCost",
    label: "Desc Cost",
  },
];

export const initialBrandsFilter = {
  Donnafugata: false,
  BodegasChivite: false,
  DomaineClarenceDillon: false,
  Bodegas: false,
  SantaCarolina: false,
  Reserva: false,
  Fairview: false,
  FincaNueva: false,
  FeudidiSanGregorio: false,
  Demuerte: false,
  PagosdelRey: false,
  Frescobaldi: false,
  DemocraticWines: false,
  Giuaani: false,
  RawsonsRetreat: false,
  NOA: false,
  AchavalFerrer: false,
  JosephDrouhin: false,
  Trapiche: false,
  Valdesil: false,
  JeanPierreMoueix: false,
  DominiodePingus: false,
  RosebankDistillery: false,
  WritersTears: false,
  TheIrishman: false,
  Bellevoye: false,
  Cardhu: false,
  Bells: false,
  Nikka: false,
  Deanston: false,
  JohnnieWalker: false,
  TullamoreDew: false,
  Kavalan: false,
  Talisker: false,
  Tobermory: false,
  Davidoff: false,
  Monnet: false,
  ThomasHine: false,
  Lheraud: false,
  Roullet: false,
  Hennessy: false,
  Praskoveyawinery: false,
  Frapin: false,
  Martell: false,
  RemyMartin: false,
  Camus: false,
  Onegin: false,
  GlobefillInc: false,
  Beluga: false,
  Mamont: false,
  Danzka: false,
  Neft: false,
  Royal: false,
  Oganyan: false,
  MontBlanc: false,
  Czechoslovakia: false,
  Ora: false,
  Summum: false,
  Sobolinaya: false,
  MagicTree: false,
  RussianSquadron: false,
  WhiteOwl: false,
  Jinro: false,
  Myagkov: false,
  JJWhitley: false,
};
